# Generated by Django 4.0.5 on 2022-08-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profilegcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilegcp',
            name='profileimg',
            field=models.TextField(default='media/blank-profile-picture.png'),
        ),
    ]
